def get_pr():
	pr={}

	pr['parent_id'] = '0'
	pr['product_ean'] = ''
	pr['manufacturer_code'] = '07.07.2025'
	pr['product_quantity'] = 0.00
	pr['unlimited'] = 0
	pr['product_availability'] = ''
	pr['product_date_added'] = '2021-01-06 10:11:51'
	pr['date_modify'] = '2021-01-06 10:11:51'
	pr['product_publish'] = 1
	pr['product_tax_id'] = 0
	pr['currency_id'] = 2
	pr['product_template'] = 'default'
	pr['product_url'] = ''
	pr['product_old_price'] = 0.0000
	pr['product_buy_price'] = 0.0000
	pr['product_price'] = 0.000000
	pr['min_price'] = 0.000000
	pr['different_prices'] = 0
	pr['product_weight'] = 0.0000
	pr['image'] = ''
	pr['product_manufacturer_id'] = 0
	pr['product_is_add_price'] = 0
	pr['add_price_unit_id'] = 3
	pr['average_rating'] = 0.00
	pr['reviews_count'] = 0
	pr['delivery_times_id'] = 0
	pr['hits'] = 0
	pr['weight_volume_units'] = 32
	pr['basic_price_unit_id'] = 3
	pr['label_id'] = 0
	pr['vendor_id'] = 0
	pr['access'] = 1
	pr['name_en-GB'] = ''
	pr['alias_en-GB'] = ''
	pr['short_description_en-GB'] = ''
	pr['description_en-GB'] = ''
	pr['meta_title_en-GB'] = ''
	pr['meta_description_en-GB'] = ''
	pr['meta_keyword_en-GB'] = ''
	pr['name_ru-RU'] = 'ФИО'
	pr['alias_ru-RU'] = 'reestr'
	pr['short_description_ru-RU'] = 'кратко'
	pr['description_ru-RU'] = 'подробно'
	pr['meta_title_ru-RU'] = ''
	pr['meta_description_ru-RU'] = ''
	pr['meta_keyword_ru-RU'] = ''
	pr['extra_field_1'] = ''
	pr['extra_field_2'] = '0'
	return pr
